package methods

const (
	DbHosts            string = "db.hosts"
	DbServices         string = "db.services"
	DbVulns            string = "db.vulns"
	DbWorkspaces       string = "db.workspaces"
	DbCurrentWorkspace string = "db.current_workspace"
	DbGetWorkspace     string = "db.get_workspace"
	DbSetWorkspace     string = "db.set_workspace"
	DbDelWorkspace     string = "db.del_workspace"
	DbAddWorkspace     string = "db.add_workspace"
	DbGetHost          string = "db.get_host"
	DbReportHost       string = "db.report_host"
	DbReportService    string = "db.report_service"
	DbGetService       string = "db.get_service"
	DbGetNote          string = "db.get_note"
	DbGetClient        string = "db.get_client"
	DbReportClient     string = "db.report_client"
	DbReportNote       string = "db.report_note"
	DbNotes            string = "db.notes"
	DbGetRef           string = "db.get_ref"
	DbDelVuln          string = "db.del_vuln"
	DbDelNote          string = "db.del_note"
	DbDelService       string = "db.del_service"
	DbDelHost          string = "db.del_host"
	DbReportVuln       string = "db.report_vuln"
	DbEvents           string = "db.events"
	DbReportEvent      string = "db.report_event"
	DbReportLoot       string = "db.report_loot"
	DbLoots            string = "db.loots"
	DbReportCred       string = "db.report_cred"
	DbCreds            string = "db.creds"
	DbImportData       string = "db.import_data"
	DbGetVuln          string = "db.get_vuln"
	DbClients          string = "db.clients"
	DbDelClient        string = "db.del_client"
	DbDriver           string = "db.driver"
	DbConnect          string = "db.connect"
	DbStatus           string = "db.status"
	DbDisconnect       string = "db.disconnect"
)
